name: store_it
description: A Flutter application to showcase different state management approaches.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx: ^0.3.9+3
  flutter_mobx: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^0.3.10+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/product-image-placeholder.png

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap/Asap-Bold.ttf
          weight: 900
        - asset: assets/fonts/Asap/Asap-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Asap/Asap-Medium.ttf
          weight: 600
        - asset: assets/fonts/Asap/Asap-Regular.ttf
          weight: 400
