name: store_it
description: A Flutter application to showcase different state management approaches.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  git: ^1.0.1
  t_stats: ^2.0.0
  logging: ^0.11.3+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/product-image-placeholder.png

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap/Asap-Bold.ttf
          weight: 900
        - asset: assets/fonts/Asap/Asap-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Asap/Asap-Medium.ttf
          weight: 600
        - asset: assets/fonts/Asap/Asap-Regular.ttf
          weight: 400
